name: client_khachhang
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0
  latlong2: ^0.9.1   
  geolocator: ^10.1.0
  http: ^1.1.0
  cached_network_image: ^3.3.0
  geocoding: ^3.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/welcome/welcome-image.png
    - assets/welcome/welcome-image-1.png
    - assets/login_form/google.png
    - assets/banking/ACBank_logo.svg.png
    - assets/banking/Agribank_logo.png
    - assets/banking/BIDV_logo.png
    - assets/banking/HDBank_logo.jpg
    - assets/banking/HSBC_logo.jpg
    - assets/banking/LPBank_logo.png
    - assets/banking/MB_logo.png
    - assets/banking/Sacombank_logo.png
    - assets/banking/SHB_logo.png
    - assets/banking/ShinhanBank_logo.png
    - assets/banking/StandardCharteredVietnam_logo.jpg
    - assets/banking/Techcombank_logo.png
    - assets/banking/TPBank_logo.png
    - assets/banking/VIB_logo.png
    - assets/banking/Vietcombank_logo.png
    - assets/banking/ViettinBank_logo.png
    - assets/banking/VPB_logo.jpg
    - assets/banking/WooriBankVietnam_logo.jpg
